# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZXDnQxa__dRnEHLiyx0KlPnDIokfSkJ
"""

first  = input(str("Enter your first name"))
middle = input(str("Enter your second name"))
last = input(str("Enter your second name"))
print(first , middle , last)

"""generate a cod"""